version: "3.8"

services:
  databse:
    image: postgres 
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 984855
        POSTGRES_DB: postgres

